#!/bin/bash
# Stand-in for passwd --lock and passwd --unlock, with the behaviour of
# shadow 4.17 measured in a scratch root:
#
#   for f in '!' '*' 'U6aMy0wojraho' '!U6aMy0wojraho' ''; do ... \
#       unshare -r passwd --root "$dir" -u root; done
#
#   field '!'              -u  exit 3, field unchanged, "unlocking the
#                              password would result in a passwordless
#                              account"
#   field '*'              -u  exit 0, field unchanged
#   field '!<hash>'        -u  exit 0, field '<hash>'
#   any field              -l  exit 0, '!' prefixed unless already there
echo "passwd $*" >> "${STUB_LOG:?}"

action=
user=
while [[ $# -gt 0 ]]; do
    case $1 in
        -l|--lock)   action=lock;   shift ;;
        -u|--unlock) action=unlock; shift ;;
        -*)          shift ;;
        *)           user=$1; shift ;;
    esac
done

field=$(awk -F: -v user="${user:?}" '$1 == user { print $2 }' "${SHADOW_FILE:?}")

case $action in
    lock)
        [[ "$field" == '!'* ]] || field="!$field"
        ;;
    unlock)
        if [[ "$field" == '!' ]]; then
            echo "passwd: unlocking the password would result in a passwordless account." >&2
            exit 3
        fi
        field=${field#!}
        ;;
    *)  exit 1 ;;
esac

awk -F: -v user="$user" -v field="$field" 'BEGIN { OFS=":" }
    $1 == user { $2 = field }
    { print }' "$SHADOW_FILE" > "$SHADOW_FILE.new"
mv "$SHADOW_FILE.new" "$SHADOW_FILE"
